// Generated by CoffeeScript 1.10.0
(function() {
  this.tsss = function() {
    return $('#p1').text('???');
  };

  $(function() {
    var h, ws;
    h = window.location.host;
    ws = new WebSocket("ws://" + h + "/ws_node_status");
    return ws.onmessage = function(e) {
      var msg, pert;
      msg = JSON.parse(e.data);
      pert = msg.node_status.localhost;
      $('.chart').data('easyPieChart').update(pert);
      $('#percent1').text(pert);
      console.log(msg);
      return ws.send('alive');
    };
  });

  $(function() {
    return $('.chart').easyPieChart({
      animate: 600,
      size: 200,
      barColor: '#ef1e25',
      lineWidth: 5
    });
  });

}).call(this);

//# sourceMappingURL=rdc.js.map
